package onlineBookShopApp;


/**
* onlineBookShopApp/book.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookShop.idl
* Friday, 10 December, 2010 10:12:22 AM IST
*/

public final class book implements org.omg.CORBA.portable.IDLEntity
{
  public String isbnNo = null;
  public String bookName = null;
  public String authorName = null;
  public String publisherName = null;
  public float bookPrice = (float)0;
  public int qtAvail = (int)0;
  public int qtTotal = (int)0;

  public book ()
  {
  } // ctor

  public book (String _isbnNo, String _bookName, String _authorName, String _publisherName, float _bookPrice, int _qtAvail, int _qtTotal)
  {
    isbnNo = _isbnNo;
    bookName = _bookName;
    authorName = _authorName;
    publisherName = _publisherName;
    bookPrice = _bookPrice;
    qtAvail = _qtAvail;
    qtTotal = _qtTotal;
  } // ctor

} // class book
