package onlineBookShopApp;

/**
* onlineBookShopApp/bookShopHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookShop.idl
* Friday, 10 December, 2010 10:12:22 AM IST
*/

public final class bookShopHolder implements org.omg.CORBA.portable.Streamable
{
  public onlineBookShopApp.bookShop value = null;

  public bookShopHolder ()
  {
  }

  public bookShopHolder (onlineBookShopApp.bookShop initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = onlineBookShopApp.bookShopHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    onlineBookShopApp.bookShopHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return onlineBookShopApp.bookShopHelper.type ();
  }

}
