package onlineBookShopApp;


/**
* onlineBookShopApp/booksHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookShop.idl
* Thursday, 9 December, 2010 1:53:44 PM IST
*/

public final class booksHolder implements org.omg.CORBA.portable.Streamable
{
  public onlineBookShopApp.book value[] = null;

  public booksHolder ()
  {
  }

  public booksHolder (onlineBookShopApp.book[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = onlineBookShopApp.booksHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    onlineBookShopApp.booksHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return onlineBookShopApp.booksHelper.type ();
  }

}
