package onlineBookShopApp;


/**
* onlineBookShopApp/bookShop.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookShop.idl
* Friday, 10 December, 2010 10:12:22 AM IST
*/

public interface bookShop extends bookShopOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface bookShop
