package onlineBookShopApp;


/**
* onlineBookShopApp/bookShopOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookShop.idl
* Friday, 10 December, 2010 10:12:22 AM IST
*/

public interface bookShopOperations 
{
  onlineBookShopApp.book search_By_isbnNo (String isbn) throws onlineBookShopApp.Unknown;
  onlineBookShopApp.book search_By_bookName (String bname) throws onlineBookShopApp.Unknown;
  onlineBookShopApp.book search_By_authorName (String aname) throws onlineBookShopApp.Unknown;
  int order_Books (onlineBookShopApp.invoiceReturn ivR) throws onlineBookShopApp.Unknown;
  onlineBookShopApp.invoiceReturn get_and_show_Invoice () throws onlineBookShopApp.Unknown;
} // interface bookShopOperations
