package onlineBookShopApp;


/**
* onlineBookShopApp/invoiceReturn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookShop.idl
* Friday, 10 December, 2010 10:12:22 AM IST
*/

public final class invoiceReturn implements org.omg.CORBA.portable.IDLEntity
{
  public String isbnNo = null;
  public String bookName = null;
  public String authorName = null;
  public String publisherName = null;
  public float bookPrice = (float)0;
  public int qtRequired = (int)0;
  public float totalPrice = (float)0;
  public String address = null;

  public invoiceReturn ()
  {
  } // ctor

  public invoiceReturn (String _isbnNo, String _bookName, String _authorName, String _publisherName, float _bookPrice, int _qtRequired, float _totalPrice, String _address)
  {
    isbnNo = _isbnNo;
    bookName = _bookName;
    authorName = _authorName;
    publisherName = _publisherName;
    bookPrice = _bookPrice;
    qtRequired = _qtRequired;
    totalPrice = _totalPrice;
    address = _address;
  } // ctor

} // class invoiceReturn
