package onlineBookShopApp;


/**
* onlineBookShopApp/Unknown.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bookShop.idl
* Friday, 10 December, 2010 10:12:22 AM IST
*/

public final class Unknown extends org.omg.CORBA.UserException
{

  public Unknown ()
  {
    super(UnknownHelper.id());
  } // ctor


  public Unknown (String $reason)
  {
    super(UnknownHelper.id() + "  " + $reason);
  } // ctor

} // class Unknown
